<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>PinguApps.Aspire.Hosting.Railway</PackageId>
    <AssemblyName>PinguApps.Aspire.Hosting.Railway</AssemblyName>
    <Description>Railway integration for Aspire.</Description>
    <EnableAspireIntegrationAnalyzers>true</EnableAspireIntegrationAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
